"""initial_migration

Revision ID: 5d070cc25fe8
Revises:
Create Date: 2026-01-29 15:26:34.935883

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5d070cc25fe8'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claude_messages_session_id'), table_name='claude_messages')
    op.drop_index(op.f('ix_claude_messages_session_timestamp'), table_name='claude_messages')
    op.drop_table('claude_messages')
    op.drop_index(op.f('ix_claude_sessions_last_activity'), table_name='claude_sessions')
    op.drop_index(op.f('ix_claude_sessions_project'), table_name='claude_sessions')
    op.drop_index(op.f('ix_claude_sessions_saved_at'), table_name='claude_sessions')
    op.drop_table('claude_sessions')
    op.drop_column('organization_members', 'avatar_url')
    op.alter_column('session_activities', 'session_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.create_index(op.f('ix_session_activities_activity_type'), 'session_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_session_activities_created_at'), 'session_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_session_activities_session_id'), 'session_activities', ['session_id'], unique=False)
    op.create_index('ix_tasks_agent', 'tasks', ['agent_id'], unique=False)
    op.create_index(op.f('ix_tasks_agent_id'), 'tasks', ['agent_id'], unique=False)
    op.alter_column('users', 'oauth_provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'oauth_provider_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.alter_column('users', 'oauth_provider_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'oauth_provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_tasks_agent_id'), table_name='tasks')
    op.drop_index('ix_tasks_agent', table_name='tasks')
    op.drop_index(op.f('ix_session_activities_session_id'), table_name='session_activities')
    op.drop_index(op.f('ix_session_activities_created_at'), table_name='session_activities')
    op.drop_index(op.f('ix_session_activities_activity_type'), table_name='session_activities')
    op.alter_column('session_activities', 'session_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.add_column('organization_members', sa.Column('avatar_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_table('claude_sessions',
    sa.Column('session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('project_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('total_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estimated_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('message_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_activity', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('saved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('session_id', name=op.f('claude_sessions_pkey'))
    )
    op.create_index(op.f('ix_claude_sessions_saved_at'), 'claude_sessions', ['saved_at'], unique=False)
    op.create_index(op.f('ix_claude_sessions_project'), 'claude_sessions', ['project_name'], unique=False)
    op.create_index(op.f('ix_claude_sessions_last_activity'), 'claude_sessions', ['last_activity'], unique=False)
    op.create_table('claude_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('message_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tool_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tool_input', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('input_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('output_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['claude_sessions.session_id'], name=op.f('claude_messages_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('claude_messages_pkey'))
    )
    op.create_index(op.f('ix_claude_messages_session_timestamp'), 'claude_messages', ['session_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_claude_messages_session_id'), 'claude_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###
